# USE codeup_test_db;
#
# CREATE TABLE UserTable (
#                          id INT UNSIGNED NOT NULL AUTO_INCREMENT,
#
#                          username VARCHAR(50),
#                          email  VARCHAR(100) NOT NULL,
#                          password  VARCHAR(100) NOT NULL,
#                          PRIMARY KEY (id)
# );
#
# INSERT INTO UserTable( User_id,username, email, password) VALUES
# (1,'kuwan2b','kuwan.barne@gmail.com','Shenderian12');
#

#
# CREATE TABLE AdsTable (
#                         AD_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
#                        title VARCHAR (225)
#                         Description TEXT NOT NULL,
#                         USER_id INT UNSIGNED NOT NULL,
#                         PRIMARY KEY (id),
#                         FOREIGN KEY (ad_id) REFERENCES UserTable (id)
# );
# CREATE TABLE category (
#                           id INT UNSIGNED NOT NULL AUTO_INCREMENT,
#
#                         name VARCHAR(255),
#                         PRIMARY KEY (id)
# );
#
# INSERT INTO category(category_id,name) VALUES
# (1,'Help Wanted'),
# (2,'Giveaway'),
# (3,'Furniture'),
# (4,'Free'),
#  (5,'Bikes')
#  ;
#
# CREATE TABLE  ads_cate (
#                              ad_id INTEGER UNSIGNED NOT NULL,
#                              category_id INTEGER UNSIGNED NOT NULL,
#                              FOREIGN KEY (ad_id) REFERENCES AdsTable (id),
#                              FOREIGN KEY (category_id) REFERENCES category(id)
#
#
#
#
#
# );
#
#
# -- MySQL Script generated by MySQL Workbench
# -- Tue Mar  2 15:38:46 2021
# -- Model: New Model    Version: 1.0
# -- MySQL Workbench Forward Engineering
#
#
# -- -----------------------------------------------------
# -- Schema mydb
# -- -----------------------------------------------------
#
# -- -----------------------------------------------------
# -- Schema mydb
# -- -----------------------------------------------------
#
#
# -- -----------------------------------------------------
# -- Table `mydb`.`create_questions`
# -- -----------------------------------------------------
use join_test_db;
CREATE TABLE IF NOT EXISTS create_questions (
                                                         id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                         create_questionsID INT UNSIGNED NOT NULL,
                                                         questions VARCHAR(10000) NOT NULL,
                                                         PRIMARY KEY (id));


-- -----------------------------------------------------
-- Table `mydb`.`create_answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS create_answer (
                                                      `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                      `create_answerID` INT UNSIGNED NOT NULL,
                                                      `answers` VARCHAR(10000) NOT NULL,
                                                      PRIMARY KEY (`id`), FOREIGN KEY (`create_answerID`)
                                                          REFERENCES privilages (`admin_id`));



-- -----------------------------------------------------
-- Table `mydb`.`quest_answ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS quest_answ(
                                                   `questions_ID` INT UNSIGNED NOT NULL,
                                                   `answers_ID` INT UNSIGNED NOT NULL,

                                                       FOREIGN KEY (`questions_ID`)
                                                           REFERENCES create_questions (`id`),

                                                       FOREIGN KEY (`answers_ID`)
                                                           REFERENCES create_answer (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`TEST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TEST (
                                             `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                             `takeTest_ID` INT UNSIGNED NOT NULL,
                                             `question_id` INT UNSIGNED NOT NULL,
                                             `answers` VARCHAR(10000) NOT NULL,
                                             PRIMARY KEY (`id`),

                                                 FOREIGN KEY (`question_id`)
                                                     REFERENCES quest_answ (`questions_ID`)
                                        );


-- -----------------------------------------------------
-- Table `mydb`.`privilages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS privilages (
                                                   `user_id` INT UNSIGNED NOT NULL,
                                                   `admin_id` INT UNSIGNED NOT NULL,

                                                       FOREIGN KEY (`admin_id`)
                                                           REFERENCES create_questions (`id`),
                                                       FOREIGN KEY (user_id)
                                                           REFERENCES `TEST` (id)
);


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS user(
                                             `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                             `user_id` INT UNSIGNED NOT NULL,
                                             `admin_id` INT UNSIGNED NOT NULL,
                                             `user_firstname` VARCHAR(45) NOT NULL,
                                             `user_lastname` VARCHAR(45) NOT NULL,
                                             PRIMARY KEY (`id`),  FOREIGN KEY (`admin_id`)
                                                 REFERENCES privilages (`admin_id`)
    ,
                                             FOREIGN KEY (`user_id`)
                                                 REFERENCES privilages (`user_id`));





